# Generated by Django 3.0.4 on 2020-05-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200503_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
