# Generated by Django 3.0.4 on 2020-05-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200503_2133'),
        ('main_app', '0004_auto_20200504_0953'),
    ]

    operations = [
    ]
