# Generated by Django 3.0.4 on 2020-05-04 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_merge_20200504_1000'),
        ('main_app', '0006_post_created_at'),
    ]

    operations = [
    ]
