# Generated by Django 3.0.5 on 2020-05-05 23:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0007_merge_20200504_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='challenge',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='ChallengeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=200)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
