# Generated by Django 3.0.5 on 2020-05-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('M', 'meetup'), ('P', 'python'), ('D', 'django'), ('Q', 'postgresql'), ('J', 'javascript'), ('N', 'node.js'), ('E', 'express'), ('G', 'mongodb'), ('H', 'html'), ('C', 'css'), ('O', 'other')], default='M', max_length=1)),
            ],
        ),
    ]
